### ISSUE TITLE
DenseNets do not match paper implementation

### ISSUE THREAD

**Issue by PabloRR100** [facebookresearch/mixup-cifar10#5]
Hi,

Similar issue that happened with ResNets. #3 

The implementation on densnet.py follow structures that are not mentioned in the paper.
There are not ResNet 121, 169, 201, 161 for CIFAR and the one called densenet_cifar layers doesn't match the original paper.  

Furthermore, densenet3.py only works for DenseNets-BC. They don't match the number of parameters reported by the authors on simple DenseNets - simple ResNet should output 16 feature maps after the first convolution instead of 2k.

I have commited on commit 5db867f on #4 an implementation on DenseNet to fit every combination reported in the original paper. They match the architectures reported in the paper:

`'''
    DenseNets implemented on the paper <https://arxiv.org/pdf/1608.06993.pdf>
    
    +-------------+-------------+-------+--------------+
    |    Model    | Growth Rate | Depth | M. of Params |
    +-------------+-------------+-------+--------------+
    |  DenseNet   |     12      |  40   |     1.02     |
    +-------------+-------------+-------+--------------+
    |  DenseNet   |     12      |  100  |     6.98     |
    +-------------+-------------+-------+--------------+
    |  DenseNet   |     24      |  100  |    27.249    |
    +-------------+-------------+-------+--------------+
    | DenseNet-BC |     12      |  100  |    0.769     |
    +-------------+-------------+-------+--------------+
    | DenseNet-BC |     24      |  250  |    15.324    |
    +-------------+-------------+-------+--------------+
    | DenseNet-BC |     40      |  190  |    25.624    |
    +-------------+-------------+-------+--------------+
    
    '''`

**Comment by ynd** [comment]
See #4.
